/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("journal_entries").del();
  await knex("journal_entries").insert([
    {
      user_id: 3,
      entry_type_id: 1,
      workout_type_id: 1,
      workout_category_id: 1,
      length_hours: 1,
      length_minutes: 30,
      time_of_day: "Aamu",
      intensity: 1,
      details: "Treenattu on",
      date: new Date(2024, 1, 1, 0, 0),
      created_at: new Date(2024, 1, 1, 0, 0),
    },
    {
      user_id: 3,
      entry_type_id: 2,
      details: "Lepopäivä",
      date: new Date(2024, 1, 2, 0, 0),
      created_at: new Date(2024, 1, 2, 0, 0),
    },
    {
      user_id: 3,
      entry_type_id: 3,
      details: "Sairaana",
      date: new Date(2024, 1, 3, 0, 0),
      created_at: new Date(2024, 1, 3, 0, 0),
    },
    {
      user_id: 3,
      entry_type_id: 1,
      workout_type_id: 1,
      workout_category_id: 1,
      length_hours: 1,
      length_minutes: 30,
      time_of_day: "Aamu",
      intensity: 1,
      details: "Treeni #1",
      date: new Date(2024, 1, 4, 0, 0),
      created_at: new Date(2024, 1, 4, 0, 0),
    },
    {
      user_id: 3,
      entry_type_id: 1,
      workout_type_id: 1,
      workout_category_id: 1,
      length_hours: 1,
      length_minutes: 30,
      time_of_day: "Aamu",
      intensity: 1,
      details: "Treeni #2",
      date: new Date(2024, 1, 4, 0, 0),
      created_at: new Date(2024, 1, 4, 0, 0),
    },
    {
      user_id: 3,
      entry_type_id: 1,
      workout_type_id: 1,
      workout_category_id: 1,
      length_hours: 1,
      length_minutes: 30,
      time_of_day: "Aamu",
      intensity: 1,
      details: "Treeni #1",
      date: new Date(2024, 1, 5, 0, 0),
      created_at: new Date(2024, 1, 5, 0, 0),
    },
    {
      user_id: 3,
      entry_type_id: 1,
      workout_type_id: 1,
      workout_category_id: 1,
      length_hours: 3,
      length_minutes: 0,
      time_of_day: "Päivä",
      intensity: 2,
      details: "Treeni #2",
      date: new Date(2024, 1, 5, 0, 0),
      created_at: new Date(2024, 1, 5, 0, 0),
    },
    {
      user_id: 3,
      entry_type_id: 1,
      workout_type_id: 1,
      workout_category_id: 1,
      length_hours: 2,
      length_minutes: 30,
      time_of_day: "Ilta",
      intensity: 3,
      details: "Treeni #3",
      date: new Date(2024, 1, 5, 0, 0),
      created_at: new Date(2024, 1, 5, 0, 0),
    },
    {
      user_id: 3,
      entry_type_id: 1,
      workout_type_id: 2,
      workout_category_id: 1,
      length_hours: 0,
      length_minutes: 30,
      time_of_day: "Aamu",
      intensity: 3,
      details: "Treeni 1",
      date: new Date(2024, 1, 6, 0, 0),
      created_at: new Date(2024, 1, 6, 0, 0),
    },
    {
      user_id: 3,
      entry_type_id: 1,
      workout_type_id: 3,
      workout_category_id: 1,
      length_hours: 1,
      length_minutes: 45,
      time_of_day: "Päivä",
      intensity: 3,
      details: "Treeni 1",
      date: new Date(2024, 1, 7, 0, 0),
      created_at: new Date(2024, 1, 7, 0, 0),
    },
    {
      user_id: 3,
      entry_type_id: 1,
      workout_type_id: 1,
      workout_category_id: 2,
      length_hours: 1,
      length_minutes: 30,
      time_of_day: "Ilta",
      intensity: 5,
      details: "Treeni 1",
      date: new Date(2024, 1, 8, 0, 0),
      created_at: new Date(2024, 1, 8, 0, 0),
    },
    {
      user_id: 3,
      entry_type_id: 1,
      workout_type_id: 1,
      workout_category_id: 3,
      length_hours: 1,
      length_minutes: 30,
      time_of_day: "Päivä",
      intensity: 4,
      details: "Treeni 1",
      date: new Date(2024, 1, 9, 0, 0),
      created_at: new Date(2024, 1, 9, 0, 0),
    },
  ]);
};
