GET http://localhost:3001/journal_entry/options HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InN0dWRlbnRAZXhhbXBsZS5jb20iLCJ1c2VyX2lkIjozLCJyb2xlIjozLCJpYXQiOjE3MTI4NTcyMjR9.ohXku8rhUTlbM7C3Cu6eB29JBVGmaI5hepion1JmPo8
content-type: application/json