services:
  urheilupaivakirja-demo:
    container_name: urheilupaivakirja-demo
    image: urheilupaivakirja-demo
    environment:
      DB_HOST: host.docker.internal
      DB_USER: root
      DB_PASS: root
      DB_DATABASE: urheilu_testi
      DB_TYPE: mysql2
      DB_PORT: 3306
      PORT: 3001
      SECRET: salainensalasanainen
      FRONTEND_URL: http://localhost:5173
      BCRYPTSALT: 10
      EMAIL_USERNAME:
      EMAIL_PASSWORD:
      EMAIL_HOST:
      FROM_EMAIL:
      EMAIL_PORT: 465
      NODE_ENV: production
    ports:
    - 3001:3001
