GET http://localhost:3001/journal HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImtheXR0YWphQGV4YW1wbGUuY29tIiwidXNlcl9pZCI6Miwicm9sZSI6MywiaWF0IjoxNzEyNTEwMDA0fQ.vrVAnfOxWueU9_3OVzUh6jXmEabNAdwYki34WHaFxJQ
content-type: application/json